# Generated by Django 5.2.14 on 2026-05-10 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_comment_submitted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='submitted_by',
        ),
    ]
