# Generated by Django 5.2.9 on 2026-01-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_closefriends_closefrienditem_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
