# Generated by Django 5.2.9 on 2026-01-12 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowaccounts', '0003_profile'),
        ('home', '0003_alter_comment_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.event')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowaccounts.profile')),
            ],
        ),
    ]
