# Generated by Django 5.2.9 on 2026-01-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
