# Generated by Django 5.2.9 on 2026-01-12 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowaccounts', '0003_profile'),
        ('home', '0005_alter_membership_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='to_whom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_owner', to='flowaccounts.profile'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
