# Generated by Django 5.2.9 on 2026-01-13 14:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_comment_user_comment_profile_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CloseFriends',
            new_name='Friend',
        ),
        migrations.RenameModel(
            old_name='CloseFriendItem',
            new_name='FriendItem',
        ),
        migrations.RenameField(
            model_name='frienditem',
            old_name='close_friend',
            new_name='friend',
        ),
    ]
