# Generated by Django 5.2.9 on 2026-01-13 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowaccounts', '0003_profile'),
        ('home', '0008_rename_closefriends_friend_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='fallback.png', upload_to='')),
                ('date_posted', models.DateTimeField()),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flowaccounts.profile')),
            ],
        ),
    ]
