# Generated by Django 5.2.9 on 2026-02-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_story'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='img',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_submitted',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='date_posted',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
