# Generated by Django 5.2.9 on 2026-02-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_img_story_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
