# Generated by Django 5.2.9 on 2026-02-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_story_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
