# Generated by Django 5.2.9 on 2026-02-16 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_frienditem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='frienditem',
            unique_together=set(),
        ),
    ]
