# Generated by Django 5.2.9 on 2026-02-16 10:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_frienditem_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='frienditem',
            unique_together={('friend', 'user')},
        ),
    ]
