# Generated by Django 5.2.14 on 2026-05-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowaccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
